### ISSUE TITLE
Workflow improvement - increment Chart.yaml version when updating values.yaml

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#1023]
This is proposing a workflow improvement for chart maintainers - increment Chart.yaml version when updating values.yaml

## Expected Behaviour

Given the following values.yaml:

```yaml
apiVersion: v1
appVersion: "1.0"
description: inlets-operator for Kubernetes
name: inlets-operator
version: 0.17.9
keywords:
- networking
- loadbalancer
- ingress
- selfhosting
- tunnels
- inlets
```

I'll see new images put into values.yaml, from `arkade chart upgrade`, but the Chart.yaml always needs bumping too and that's a manual task.

I'd suggest always bumping the minor patch version, and if it's a bigger change the user can just edit the file.

```
arkade chart bump
```

## Current Behaviour

In the case of OpenFaaS, if 6 repos change then I have to edit 6 files manually.
