### ISSUE TITLE
Make Ingress generators K8s 1.18 compatible

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#110]
In Kubernetes 1.18 the Ingress definitions have changed slightly. 

In particular the @paurosello mentioned the change about `ingressClass` becoming part of the spec, instead of being an annotation.

If we can add both, perhaps that will help keep backwards compatibility for the time being?

https://kubernetes.io/docs/setup/release/notes/#extending-ingress-with-and-replacing-a-deprecated-annotation-with-ingressclass

Alex

**Comment by Waterdrips** [comment]
We can't add both. A 1.18 cluster: 
```
Error from server (Invalid): error when creating "/tmp/.arkade/temp_openfaas_ingress.yaml": Ingress.extensions "openfaas-gateway" is invalid: annotations.kubernetes.io/ingress.class: Invalid value: "nginx": can not be set when the class field is also set
```

a 1.17 gives a validation error if the field exists but we can set `--validate-false` to get past that.

We might have to get the k8s version when installing ingress and decide if we are doing annotation or field. 

Ill have a look at checking the version using the go client or something..

**Comment by alexellis** [comment]
You can't set an annotation for backwards compatibility? Since when were annotations something the Kubernetes API rejected deployments over. 

If there's no workaround, then like you say the code will need an additional flag or test to determine the API version.

@viveksyngh cc

**Comment by alexellis** [comment]
Please don't add a dependency to the Kubernetes go client to arkade, the size of the binary will balloon out of control. 

Rob Scott is saying that it *is supported* to have both the annotation and the spec, despite the hard error. Perhaps the best solution for arkade is to run `kubectl apply` with `--validate=false`.

https://twitter.com/robertjscott/status/1262053313786216449?s=20

For the Ingress Operator (that creates ingress, we have the Kubernetes Go client already there, so it seems like we should either set both there, or set either depending on the API server version. https://github.com/openfaas-incubator/ingress-operator/issues/27)

**Comment by aledbf** [comment]
The `validate=false` will help to bypass the validation https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/networking/validation/validation.go#L216

**Comment by alexellis** [comment]
https://twitter.com/robertjscott/status/1262053313786216449?s=20

<img width="603" alt="Screenshot 2020-05-17 at 17 28 45" src="https://user-images.githubusercontent.com/6358735/82154154-e470bf80-9863-11ea-925a-eed0999461cd.png">

It's unclear whether this is intended or unintended behaviour from the K8s team, it certainly doesn't look like both the spec attribute and the legacy annotation are compatible. 

Thanks @aledbf for echoing what @Waterdrips said above. We should try this for arkade, and then see what kind of errors we get in the ingress-operator and decide how to move on from there.

**Comment by alexellis** [comment]
> IngressClassName is the name of the IngressClass cluster resource. The associated IngressClass defines which controller will implement the resource. This replaces the deprecated `kubernetes.io/ingress.class` annotation. For backwards compatibility, when that annotation is set, it must be given precedence over this field. The controller may emit a warning if the field and annotation have different values. Implementations of this API should ignore Ingresses without a class specified. An IngressClass resource may be marked as default, which can be used to set a default value for this field. For more information, refer to the IngressClass documentation.

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#ingressspec-v1beta1-networking-k8s-io

**Comment by Waterdrips** [comment]
I was already using `--validate=false` 

``` kubectl apply --validate=false -f /tmp/.arkade/temp_openfaas_ingress.yaml 
Error from server (Invalid): error when creating "/tmp/.arkade/temp_openfaas_ingress.yaml": Ingress.extensions "openfaas-gateway" is invalid: annotations.kubernetes.io/ingress.class: Invalid value: "nginx": can not be set when the class field is also set
```

The error is ^ there

the yaml: 

```yaml
apiVersion: extensions/v1beta1 
kind: Ingress
metadata:
  name: openfaas-gateway
  namespace: openfaas
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: example.heyal.uk
    http:
      paths:
      - backend:
          serviceName: gateway
          servicePort: 8080
        path: /
  tls:
  - hosts:
    - example.heyal.uk
    secretName: openfaas-gateway
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: alistair@heyal.co.uk
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: example-issuer-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
```
