### ISSUE TITLE
[BUG] arkade install command is not working with KUBECONFIG environment variable

### ISSUE THREAD

**Issue by developer-guy** [alexellis/arkade#393]
If you are using the `KUBECONFIG` environment variable to define the path for the Kubernetes configuration file, the install command of the `arkade` tool is not working.

## Expected Behaviour

It should consider this environment variable to find the Kubernetes configuration file.

## Current Behaviour

It is not working with the `KUBECONFIG` environment variable.

## Steps to Reproduce (for bugs)

1. k3d create cluster demo
2. mkdir -p test-with-kubeconfig
3. cd test-with-kubeconfig
4. kubectl config view --minify --flatten > kubeconfig
5. export KUBECONFIG=./kubeconfig
6. kubectl get pods <-- it should work
7. arkade install openfaas <-- it should throw error

## Your Environment

* What Kubernetes distribution are you using?

```
kubectl version skew -oyaml
Found existing alias for "kubectl". You should use: "k"
Alias tip: k version skew -oyaml
clientVersion:
  buildDate: "2021-04-08T16:31:21Z"
  compiler: gc
  gitCommit: cb303e613a121a29364f75cc67d3d580833a7479
  gitTreeState: clean
  gitVersion: v1.21.0
  goVersion: go1.16.1
  major: "1"
  minor: "21"
  platform: darwin/amd64
serverVersion:
  buildDate: "2021-04-26T21:45:52Z"
  compiler: gc
  gitCommit: 2705431d9645d128441c578309574cd262285ae6
  gitTreeState: clean
  gitVersion: v1.21.0+k3s1
  goVersion: go1.16.2
  major: "1"
  minor: "21"
  platform: linux/amd64
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a
Darwin xxxx 19.6.0 Darwin Kernel Version 19.6.0: Mon Apr 12 20:57:45 PDT 2021; root:xnu-6153.141.28.1~1/RELEASE_X86_64 x86_64
```

* What arkade version is this?

```
arkade version
            _             _
  __ _ _ __| | ____ _  __| | ___
 / _` | '__| |/ / _` |/ _` |/ _ \
| (_| | |  |   < (_| | (_| |  __/
 \__,_|_|  |_|\_\__,_|\__,_|\___|

Get Kubernetes apps the easy way

Version: 0.7.13
Git Commit: a7418b1652e1f96c6f86985572c828a96d136836

```

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/alexellis
- [x] Yes
- [ ] No
