### ISSUE TITLE
Schedule GH Actions to identify tools dead links

### ISSUE THREAD

**Issue by yankeexe** [alexellis/arkade#609]
## Expected Behaviour

Similar to #607 ; there have been a few occasions where the versioning/naming convention of some tools has changed that breaks our CLI and we are not aware unless we run into it or someone raises an issue regarding it.

Run [GitHub actions schedule event](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule) to run `make test` every day or weekly to check if any of the download URL for tools leads to dead links.

## Current Behaviour

No identification of dead links for tools supported by arkade.

## Are you a GitHub Sponsor (Yes/No?)

Check at https://github.com/sponsors/alexellis

- [ ] Yes
- [x] No

## Possible Solution

Add GitHub Actions schedule event to run cron periodically to check for dead links.
```yaml
on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Install Go
        uses: actions/setup-go@v2

      - name: Run tests
        run: make test
```
