### ISSUE TITLE
[Feature Request] Add MetalLB

### ISSUE THREAD

**Issue by aditsachde** [alexellis/arkade#76]
If running on a set of Raspberry Pis or anywhere that does not provide a loadbalancer, we have to fall back to using host ports for Kubernetes. [MetalLB](https://metallb.universe.tf/) solves this issue by providing a bare metal load balancer implementation, and it works quite nicely I would say. I currently use it on all my clusters without any issues, and it would be great to see it added to Arkade.

The issue I see though, is that they have stopped publishing helm charts and moved to only manifests/kustomize as their officially supported deployment methods. 

Please let me know if I can help in any way.

**Comment by alexellis** [comment]
Hi, thanks for your interest in arkade. 

Most folks don't have BGP at home, so can you give the precise configuration that works for your home network? Re: helm, that's a shame, but the Kubernetes dashboard and ArgoCD are also installed by YAML manifests. 

Also, have you seen the inlets-operator? Take a look. You can get real, public IPs and it's also an LB.

**Comment by aditsachde** [comment]
I've actually been following inlets-operator since the day it was released! 😃 I just haven't had a need for a second public IP as of now. What I did with metalLB is simply apply the manifests, and then apply the following ConfigMap.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.0.2.30-10.0.2.50
```

BGP is not actually needed, it will work happily at layer 2. All my VMs run on the `10.0.2.0/24` network, so I just gave metalLB a range of 20 unused IPs in that space. From there, I can port forward from my router to the corresponding IP of the service.
