### ISSUE TITLE
Add downloads for: kubeconform, conftest and kubeval

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade#781]
## Expected Behaviour

Add downloads for: kubeconform, conftest and kubeval

## Current Behaviour

These are available in kube-tools by @stefanprodan, but we don't have them here yet

https://github.com/stefanprodan/kube-tools

The new style for arkade in GitHub makes it work in a similar way to kube-tools, but for many more CLIs:

```yaml
    - uses: alexellis/setup-arkade@v1
    - uses: alexellis/arkade-get@master
      with:
        kubectl: latest
        faas-cli: 0.14.10
    - name: check for faas-cli
      run: |
        $HOME/.arkade/bin/faas-cli version
```

## Possible Solution

See past examples of merged PRs, pick one and copy it for the above tools.

See also: https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md
