### ISSUE TITLE
Kustomize stopped working since 0.9.23

### ISSUE THREAD

**Issue by ivanivicrho** [alexellis/arkade#947]
Since release https://github.com/alexellis/arkade/releases/tag/0.9.23, an error is thrown:

```
The requested version of kustomize is not available or configured in arkade for Linux/x86_64

* Check if a binary is available from the project for your Operating System
* View the kustomize releases page: https://github.com/kubernetes-sigs/kustomize/releases
* Feel free to raise an issue at https://github.com/alexellis/arkade/issues for help
```

Doesn't matter which version of kustomize is configured, same error happens for these three:
```
        kustomize: 4.5.7
        kustomize: 5.0.3
        kustomize: 5.1.0

```

This was working until the latest release.

## Expected Behaviour
Kustomize to work

## Current Behaviour
Kustomize cannot be installed

## If requesting a CLI for "arkade get"

How many downloads does this tool have? Check at: 

https://somsubhra.github.io/github-release-stats/

If approved, are you willing to submit a pull request for this?

## Your Environment

* What Kubernetes distribution are you using?

```
kubectl version
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a

cat /etc/os-release
```

* What arkade version is this?

```
arkade version
```

**Comment by ivanivicrho** [comment]
The breaking change is that `v` prefix is now required - before this release, prefix `v` was not working, the only thing that worked was:
```
      - uses: alexellis/arkade-get@master
        with:
          kubectl: latest
          kustomize: 4.5.7
          kubeconform: v0.6.1
          helm: v3.10.3
          jq: jq-1.6
          yq: v4.34.1
```

Config that works on latest release:
```
      - uses: alexellis/arkade-get@master
        with:
          kubectl: latest
          kustomize: v4.5.7
          kubeconform: v0.6.1
          helm: v3.10.3
          jq: jq-1.6
          yq: v4.34.1
```
