### ISSUE TITLE
Installation of `kustomize` fails in GitHub Actions workflows

### ISSUE THREAD

**Issue by fjeldstad** [alexellis/arkade#956]
## Expected Behaviour

It should be (and has been) possible to install `kustomize@4.5.7` in a GitHub Actions workflow that runs on `ubuntu-latest`.

## Current Behaviour

Installation fails with the message:
```
Run alexellis/arkade-get@2adc9fbcb575e1a684e8be9744a7a9f63e02d978
  with:
    kustomize: 4.5.7
  env:
    PATH: [...]
/usr/local/bin/arkade get --progress=false --quiet=true kustomize --version 4.5.7

The requested version of kustomize is not available or configured in arkade for Linux/x8[6](https://github.com/[...])_64

* Check if a binary is available from the project for your Operating System
* View the kustomize releases page: https://github.com/kubernetes-sigs/kustomize/releases
* Feel free to raise an issue at https://github.com/alexellis/arkade/issues for help

Error: server returned status: 404
Error: The process '/usr/local/bin/arkade' failed with exit code 1
```

## Possible Solution
I don't know enough about Arkade or even Kustomize to know how to fix this. I looked at the Kustomize releases and it seems it has never published binaries for x86? For example: https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv4.5.7 - but I know for sure that this has worked before.

## Steps to Reproduce (for bugs)

Create a workflow that uses the lastest version of `alexellis/setup-arkade` and `alexellis/arkade-get` to install `kustomize@4.5.7`. Example (with action versions pinned):

```
name: Test Kustomize installation
on:
  workflow_dispatch:
jobs:
  test-kustomize-installation:
    runs-on: ubuntu-latest
    steps:
      - uses: alexellis/setup-arkade@b1816384b2260cfd2c023c6798d26075786cfc7f #v3
      - uses: alexellis/arkade-get@78214cb8d9b90e651b625cfdc6a3209539dc1353 #master per 2023-07-10
        with:
          kustomize: 4.5.7
```
